project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on-Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on-Ex03.html"
            
      - text: "In class Exercises"
        menu: 
          - text: "In class exercise 2"
            href: "in-class_Ex/In-class_Ex02/In-class_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    
format:
  html:
    theme: Cerulean
    css: styles.css
    toc: true

editor: visual

